### ISSUE TITLE
Bilingualism is missing

### ISSUE THREAD

**Issue by stephane-lapointe** [cioos-siooc/ckan#1]
### CKAN Version if known (or site URL)

All

### Please describe the expected behavior

Requesting a resource through API should return bilingual JSON data.

### Please describe the actual behavior

When interacting with CKAN API, the requested URL returns unilingual JSON data. 

### What steps can be taken to reproduce the issue? 

As an example, one could request 

http://<ckan_instance>/api/3/action/package_show?id=<id>

while changing values according to there setup.

**Comment by stephane-lapointe** [comment]
I suggest to use fluent https://github.com/ckan/ckanext-fluent

**Comment by fostermh** [comment]
I have added ckanext-fluent to the docker image. I have not done a test install yet, hoping someone else can test it. (13da17712d32f97b4adf2649c7d49da1f0ddf4ff)

**Comment by n-a-t-e** [comment]
I tested it with some examples of bilingual schema elements on the fluent website and it seems to work
