### ISSUE TITLE
citation not populated by all authors

### ISSUE THREAD

**Issue by fostermh** [cioos-siooc/ckan#106]
it seems that responsible parties with individual name set and no organization are populating the citation field but RP with organization name set are not populating the citation field

https://pac-dev1.cioos.org/ckan/dataset/ca-coos_50f11bf2-c710-446c-8230-9ebbf6dcb2a3

**Comment by fostermh** [comment]
updating the _cited_responsible_party_to_responsible_organizations function to remove blank entries from the list is likey all that is needed.

https://github.com/cioos-siooc/ckanext-cioos_theme/blob/master/ckanext/cioos_theme/plugin.py#L377-L387

**Comment by fostermh** [comment]
likely just need to make both CI_Individual xpaths into one or using '|'
https://github.com/cioos-siooc/ckanext-spatial/blob/cioos-siooc/ckanext/spatial/model/harvested_metadata.py#L759-L760

**Comment by fostermh** [comment]
@mmbutton have you had a chance to create a pr for this one? I thought you said you had something worked out.

**Comment by mmbutton** [comment]
I wasn't able to complete it as my windows setup exploded with issues once I made the code change (CKAN not starting, permission issues and all the fun stuff). As this is getting beyond frustrating to deal with I'm going to switch to a Cent OS VM next CKAN sprint and resume working on testing this. For now I have to go back to doing my ONC sprint work and can't finish this off.

**Comment by fostermh** [comment]
ok thanks.

**Comment by fostermh** [comment]
fixed
