### ISSUE TITLE
keywords are concatenated with a dash

### ISSUE THREAD

**Issue by Br-Johnson** [cioos-siooc/ckan#109]
**Describe the bug**
After entering keywords in the CIOOS metadata entry tool separated by commas, the CKAN record shows the keyword 'tags' as a single concatenated string separate by dashes.

**To Reproduce**
1. Go to 'https://cioos-siooc.github.io/metadata-entry-form/#/en/pacific/jnK2pbrIzbMBHpSiUOi8XDUeev93/-MVbHfVJc-DDbAHUqBFE' to see the keywords entered. And then reference the metadata record https://catalogue.cioospacific.ca/dataset/ca-coos_50f11bf2-c710-446c-8230-9ebbf6dcb2a3
2. Click on 'salmon-survival-fish' tag under the Metadata Source section
4. See concatenated keyword "salmon-survival-fish-health-marine-ecology-sockeye-pink-chum-coho" 

**Expected behavior**
I would have expected these to each be a separate keyword

**Screenshots**
![Screen Shot 2021-04-12 at 10 24 43 AM](https://user-images.githubusercontent.com/26495640/114435867-8c2c6580-9b79-11eb-8be7-cc441fe00062.png)

**Desktop (please complete the following information):**
 - OS: [Mac OS Catalina]
 - Browser Chrome
 - Version 89.0

**Comment by Br-Johnson** [comment]
I see the keywords need to be added 1 at a time. 

I will republish to see if this fixes it!

**Comment by fostermh** [comment]
CKAN will take whatever is entered in one keyword entity in the xml as a keyword. If entring keywords individually in the metadata-form doesn't work or is too cumbersome then I think this issue would be best addressed by the metadata-form tool.

**Comment by Br-Johnson** [comment]
This was a user error. You can't enter keywords as a string separated by commas, you have to add them one at a time. The entry tool even says this. So, never mind! all good.
