### ISSUE TITLE
Citation doesn't include all authors

### ISSUE THREAD

**Issue by Br-Johnson** [cioos-siooc/ckan#110]
**Describe the bug**
In the citation automatically created, not all the authors of the dataset are listed

**To Reproduce**
1. Go to 'https://catalogue.cioospacific.ca/dataset/ca-coos_50f11bf2-c710-446c-8230-9ebbf6dcb2a3'
3. Scroll down to 'Citation'
4. See error: 
Julian Gan, Sean Godwin, & Martin Krkosek. (2021). Hakai Institute Juvenile Salmon Program [Data set]. https://doi.org/76e20e5d-0bbc-4a0f-90c7-598a3edd4258
It looks like only those who are listed as authors and not point of contacts for data are listed. 
--

**Expected behavior**
I would have expected all the people with the role 'author' to be listed in the citation:
Brett Johnson, Julian Gan, Sean Godwin, Martin Krkosek & Brian Hunt. (2021). Hakai Institute Juvenile Salmon Program [Data set]. https://doi.org/76e20e5d-0bbc-4a0f-90c7-598a3edd4258

**Comment by Br-Johnson** [comment]
Also, the DOI is incorrect. We entered a UUID from our OBIS resource for the Dataset Identification (perhaps the wrong thing to put here) in the metadata entry tool and it looks like the Citation generator assumed that we entered a DOI and created a non-existent DOI. Might need to make it clear in the metadata entry tool to enter only DOIs without 'https://doi/org/' (eg. 10.21966/1.566666) if the citation generation automatically assumes you've entered a DOI without "https://doi.org/", which it seems to. @n-a-t-e

**Comment by fostermh** [comment]
Initial issue description appears to be a duplicate of cioos-siooc/ckan#106

**Comment by fostermh** [comment]
> Also, the DOI is incorrect. We entered a UUID from our OBIS resource for the Dataset Identification (perhaps the wrong thing to put here) in the metadata entry tool and it looks like the Citation generator assumed that we entered a DOI and created a non-existent DOI. Might need to make it clear in the metadata entry tool to enter only DOIs without 'https://doi/org/' (eg. 10.21966/1.566666) if the citation generation automatically assumes you've entered a DOI without "https://doi.org/", which it seems to. @n-a-t-e

The ckan harvester will pass through any URL unchanged but will assume a non-url string is a DOI. If you want to include a different identifier then you would have to use the full url. In this case `https://obis.org/dataset/76e20e5d-0bbc-4a0f-90c7-598a3edd4258`

**Comment by n-a-t-e** [comment]
> The ckan harvester will pass through any URL unchanged but will assume a non-url string is a DOI. If you want to include a different identifier then you would have to use the full url. In this case `https://obis.org/dataset/76e20e5d-0bbc-4a0f-90c7-598a3edd4258`

Ok, good to know this so that we can put it in the instructions on the metadata form

**Comment by fostermh** [comment]
hmmm I may have lied. 

CKAN passes it through but the javascript library that formats the citation add's the http://doi.org/ to it anyway.

**Comment by fostermh** [comment]
ok. DOI only. sending other urls will not work currently. Also the record in question has a doi. http://dx.doi.org/10.21966/1.566666

**Comment by Br-Johnson** [comment]
OK, roger that. I will make another issue in the metadata template for @n-a-t-e to update the guidance in the Dataset Identification section. 

The dataset referenced here is derived from data at that DOI you mention. It could probably use it's own DOI at some point which I think OBIS/GBIF can do for us.

Thanks guys!
