### ISSUE TITLE
Errors related to xml file harvesting

### ISSUE THREAD

**Issue by ogsletcax** [cioos-siooc/ckan#111]
- https://github.com/cioos-siooc/ckanext-cioos_theme/blob/38ef5f24afce283a4f771a3699f455e4cc73cece/ckanext/cioos_theme/plugin.py#L150 

throws an exception when value is a dict

 I could fix the previous error with `range = json.loads(value) if type(value) is not dict else value` but it seems hacky

- https://github.com/cioos-siooc/ckanext-spatial/blob/cf166a500f4cf1f6dc77155aee5c13b180dc07f5/ckanext/spatial/model/harvested_metadata.py#L1562

throws an encoding exception when accents characters are used in keywords (example: "amélioration des connaissances")

i tried to fix that with a `json.dumps(LangDict, encoding="latin1")` but ultimately i get a validation error `Validation Error: {u'Keywords': u'Tag "acc\xc4\x82\xc2\xa8s \xc4\x82\xc2\xa0 la mer" must be alphanumeric characters or symbols: -_.\''`

i doesn't work when reencoding to utf-8 as well

- when not using accents i get a validation error about eovs  Validation` Error: {u'Eov': 'Select at least one'} (__init__.py:256)`
even if it is included in the xml file https://catalogue-waf.preprod.ogsl.ca/metadata-files/test/42434268-27c0-45fb-b11b-eff5f62d99e5.xml

**Comment by ogsletcax** [comment]
@fostermh Any hints?

**Comment by fostermh** [comment]
for the first error, change 'json.load' to 'load_json' which does what you are suggesting but in a reusable function.

For the keyword / eov error I'm going to have to look into it more. I don't think I have ever tested the harvester with a french default language as I did not have an example file. I will try out your linked file and get back to you.

**Comment by fostermh** [comment]
ok so this is what I would expect to happen:
```
>>> str = u'accès à la mer'
>>> str
u'acc\xe8s \xe0 la mer'
>>> str.encode('utf-8')
'acc\xc3\xa8s \xc3\xa0 la mer'
```

This is what is actually happening
```
>>> str = u'acc\u0102\xa8s \u0102\xa0 la mer'
>>> str
u'acc\u0102\xa8s \u0102\xa0 la mer'
>>> str.encode('utf-8')
'acc\xc4\x82\xc2\xa8s \xc4\x82\xc2\xa0 la mer'
```

I don't know why the string is reading into the harvest with unicode escaped chars in it.

**Comment by fostermh** [comment]
It appears that request.get is auto detecting the encoding for the xml files based on the http headers. This is being reported incorrectly. My solution is to force UTF-8 encoding for all xml files. This appears to work for the limited files I have tested.

**Comment by fostermh** [comment]
smart atlantic double escapes their unicode characters so they are showing up as escaped unicode in ckan. I will add a regex sub to removed the double escape.
