### ISSUE TITLE
Multiple copies of same metadata record in CIOOS National CKAN

### ISSUE THREAD

**Issue by Br-Johnson** [cioos-siooc/ckan#117]
Multiple copies of the same metadata record (Hakai Juvenile Salmon Program) are in the CIOOS National CKAN. We unpublished and re-published this particular record to CIOOS Pacific a few times for testing and iteratively develop. It looks like the harverster thought they were distinct entries when likely the oldest versions should be discarded.

Steps to reproduce the behaviour:
1. Go to 'https://catalogue.cioos.ca/'
2. Search for Hakai Juvenile Salmon Program
3. Scroll down to see four copies of the same metadata 
4. CLick on each record to see different Dates for created/updated etc.

**Expected behavior**
I would expect the older versions to be replaced by the more recent version

**Screenshots**
![image](https://user-images.githubusercontent.com/26495640/120044689-2a0daf80-bfc3-11eb-929c-77e578212f0e.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version 90.0

**Comment by fostermh** [comment]
ckan appears to be detecting changes in the records pacific and adding an incrementing number to the end of the record on national. It should be updating the existing record rather than creating a new one.

**Comment by fostermh** [comment]
This appears to be fixed. it may have been related to the metadata form changing the guid when editing and resaving xml files or it might be related to the deleted datasets not propagating through ckan catalogus issue which has also be resolved.
