### ISSUE TITLE
Citation url is not matching datasets url for datasets imported from the metadata form

### ISSUE THREAD

**Issue by ogsletcax** [cioos-siooc/ckan#118]
The authority field is filled with "ca.cioos" by the metadata form tools.

The calculate_identifier method in https://github.com/cioos-siooc/ckanext-spatial/blob/e5130058fd117e8206131985ec3506c6c44bca2e/ckanext/spatial/model/harvested_metadata.py#L1565  calculate an id based on the authority field. So the resulting url is like https://catalogue.preprod.ogsl.ca/dataset/ca.cioos_656b0f87-59b7-440f-949e-84b1580c2b7c?local=fr

On ckan side the id is converted to something like https://catalogue.preprod.ogsl.ca/dataset/ca-cioos_656b0f87-59b7-440f-949e-84b1580c2b7c?local=fr)

should we change to authority value? Make it customizable in the export tool? or replace "." by "-" in the calculate_identifier method?

@fostermh @n-a-t-e @jeffcullis

**Comment by fostermh** [comment]
well isn't that interesting. I will have to look into why the '.' is converted to a '-' but my initial thought is that ckan uses a 'munge' function to clean the url's and it is doing a replace on '.'

**Comment by ogsletcax** [comment]
@fostermh indeed! munge_name function is used here https://github.com/cioos-siooc/ckanext-cioos_harvest/blob/4154ff81cf716b29ed6b224cc49c6250310822d1/ckanext/cioos_harvest/plugin.py#L310
