### ISSUE TITLE
merge point of contact and responsible parties

### ISSUE THREAD

**Issue by fostermh** [cioos-siooc/ckan#119]
It is suggested by the IYS team and developers on the metadata-entry-form that we should merge the 'point of contact' and 'responsible parties' fields in the CKAN gui into one field. This change needs discussion and signoff by all RA's before making the change. 

The proposal is to not change the underlying data, just how it is displayed in the gui at this point.

**Comment by sjbruce** [comment]
So, essentially these separate fields become one "Contacts" section that lists people, their roles and contact information?

**Comment by fostermh** [comment]
This issue is on hold pending a ckan gui review

**Comment by fostermh** [comment]
we did it as the GUI review is likely to never happen.
