### ISSUE TITLE
When a DOI is set it should be used in the citation url

### ISSUE THREAD

**Issue by ogsletcax** [cioos-siooc/ckan#124]
Currently the citation use the dataset catalog url.

It's been asked to display the DOI url (https://doi.org/10.0000/0000) in the citation when the doi field is set in metadata.

@fostermh @jeffcullis Do you think it's ok to change that behaviour?

**Comment by ogsletcax** [comment]
There are two small things to fix:
- The doi field in the metadata form has a label that is misleading: it says to enter the doi url instead of the doi code (but the harvester only understands the doi code pattern)
- Depending on the citation style, sometimes, the doi url is not used. Here is a pull request to always use the doi url when a doi is set: https://github.com/cioos-siooc/ckanext-spatial/pull/22

**Comment by fostermh** [comment]
I commented on this in the PR but then thought I should add it here so we can discuss it.

I'm not sure the problem this is trying to fix actually exists. doi's which are entered correctly under the 'unique-resource-identifier-full' key is added to the citation as doi's, as expected. Do you have an example I can look at, preferable of some xml I can harvest into my test system to compare against your production, and see if something is different?



![Screen Shot 2022-01-11 at 7 23 35 PM](https://user-images.githubusercontent.com/6304992/149058384-8cd585da-d6f0-4c60-b3c5-fd2e4a558eb1.png)

![Screen Shot 2022-01-11 at 7 23 43 PM](https://user-images.githubusercontent.com/6304992/149058382-b9b6015c-d67d-4910-b48d-ba910935e754.png)

**Comment by ogsletcax** [comment]
The snapshot you took seems fine to me.

As far as i remember, the problem was that the catalogue url (https://catalogue.preprod.ogsl.ca/dataset/xxxxxxxxx) was shown in the citation instead of doi url (https://doi.org/10.xxxx/xxxxxx). I assumed that the doi url is the url we want to share preferably when we have a doi..

**Comment by fostermh** [comment]
ok great, yes that is how I was thinking about it as well, DOI preferred when available. I will close this issue for now. feel free to re-open if something doesn't seem correct.
