### ISSUE TITLE
Special characters in abstract break citation population

### ISSUE THREAD

**Issue by jeffcullis** [cioos-siooc/ckan#127]
Through some trial and error have found a few issues with the '&' character in abstracts breaking citation population.
A bare '&' or even '\\&' in the abstract will cause the harvester to fail.
\&quot;
above will harvest, but citation doesn't populate.

**Comment by fostermh** [comment]
after some digging, it appears this is the correct behavior. In short, a '&' in the abstract is not valid xml. The '&' should be replaced with '&amp;'.

a '&quot;' does not appear to change the citation display in my local test version so I think this issues may have been resolved. closing for now. feel free to re-open if you see this happening again.
