### ISSUE TITLE
If modified date is not found in the waf, the harvesting process fails

### ISSUE THREAD

**Issue by fostermh** [cioos-siooc/ckan#134]
Reported by @ogsletcax .

When no modified date is found in the waf, the harvesting process fails. It should not.

Notes on current behaviour:
when waf is served by apache it is expected that the options +FancyIndexing +HTMLTable are set.

when waf is served by apache but behind an nginx proxy, it will fail to find the modified date because the request header “server’ will contain “nginx” instead of “apache”

**Comment by fostermh** [comment]
need an example waf to test solution.

**Comment by ogsletcax** [comment]
An example of apache file listing with FancyIndexing and HTMLTable options behind an nginx proxy:
https://catalogue-waf.preprod.ogsl.ca/metadata-files/merinov/

An example of apache file listing without formating options behind an nginx proxy:
https://catalogue-waf.ogsl.ca/metadata-files/mpo/

**Comment by fostermh** [comment]
closing this for now as it appears to work with the existing harvest setup. If more problems are found we can re-open.
