### ISSUE TITLE
Authors in citation

### ISSUE THREAD

**Issue by ogsletcax** [cioos-siooc/ckan#136]
I have been asked if author, owner, coAuthor, principalInvestigator, originator  roles only could apprear in the citation

(or ideally to select the parties shown in the citation in the metadata form, but this seems a bit hard to implement)

Do you think it would be ok to do that change?

The first option would require to modify the file:
https://github.com/cioos-siooc/ckanext-spatial/blob/1a3ff1a7bd85cb92667734cd4544ce2998b1aa98/ckanext/spatial/model/harvested_metadata.py

Also I see that authors are parsed in two different ways:

https://github.com/cioos-siooc/ckanext-spatial/blob/1a3ff1a7bd85cb92667734cd4544ce2998b1aa98/ckanext/spatial/model/harvested_metadata.py#L1397
(values['citation']['author'])
and 
https://github.com/cioos-siooc/ckanext-spatial/blob/1a3ff1a7bd85cb92667734cd4544ce2998b1aa98/ckanext/spatial/model/harvested_metadata.py#L803
(values['author'])

It is the last one that is used in infer_citation

I'm wondering why authors are parsed in two different ways and why it's values['author'] and not values['citation']['author'] that is used in infer_citation

Do you have an idea?

**Comment by ogsletcax** [comment]
@fostermh Not for now, i prefer to complete the ckan (python3) migration before.

**Comment by fostermh** [comment]
fixed by allowing contacts to be 'included in citation' or not in the metadata entry form
