### ISSUE TITLE
EOV switch from camelCase to regular text

### ISSUE THREAD

**Issue by n-a-t-e** [cioos-siooc/ckan#147]
We have been using camelCase for the EOVs in our XML files. if another organization wants to harvest our XML dataset they would expect to receive keywords in plain text with spaces instead of camel case. It would be good to add support for the full EOV titles, if this isn't already supported by CKAN.

See GOOS EOVs list: https://www.goosocean.org/index.php?option=com_content&view=article&layout=edit&id=283&Itemid=441 . Note that Nitrous is misspelled Nitrus in this list.

See https://github.com/cioos-siooc/metadata-entry-form/issues/152

**Comment by fostermh** [comment]
great. ckan already matches on the title or camelcase value so I think we are good. the match is not case-sensitive. Note the match is on English keywords only as it was decided long ago that 'eov' was not a translated field.

**Comment by n-a-t-e** [comment]
Great! then I will close this issue on the CKAN side.
