### ISSUE TITLE
Dataset Status "Historical Archive" not recognized, displays as "On Going"

### ISSUE THREAD

**Issue by sjbruce** [cioos-siooc/ckan#159]
**CKAN version**
2.9.5 (originally ingested with 2.9.3)

**Describe the bug**
After harvesting from a WAF the dataset status is displayed as "On Going" instead of "Historical Archive" as specified in the XML

**Steps to reproduce**
Harvest the following metadata record into CKAN: https://dev.cioosatlantic.ca/metadata/marine_institute_mun/seafloor_mapping_for_onshore_o_48c63.xml 

**Expected behavior**
The dataset status should display "Historical Archive"

**Additional details**
No errors are apparent when harvesting the record.  "On Going" appears to be the default value and "Historical Archive" appears to be properly specified in the CKAN schema.  XML record was generated using the CIOOS metadata form.  XML appears to be properly formatted and contains the correct value.

**Comment by fostermh** [comment]
fixed by https://github.com/cioos-siooc/ckan/pull/156 
specifically https://github.com/cioos-siooc/ckanext-cioos_harvest/commit/cab7be825b8bf6723cfcf2cdecc4d34f100a6940 and will be in v1.2 release
