### ISSUE TITLE
can not enter keywords via form gui in ckan

### ISSUE THREAD

**Issue by fostermh** [cioos-siooc/ckan#160]
when filling out a new ckan record in ckan, then keywords field will not take input. after typing and moving to the next field the keyword field goes blank.

**Comment by jacobthompson101** [comment]
Not sure if it's a related issue, but I remember a long time ago creating basic JavaScript forms connected to PHP backed and database, if one pressed the submit form button but if there was an error, then it wouldn't always repopulate the values already entered unless the form had some sort of catch variable to repopulate. Likely not the exact same issue, but maybe similar concept? Sometimes things like focus will clear form entries on websites.

**Comment by fostermh** [comment]
fixed by [ce7d3b99057da1d6fb97c1e0b54e4a44040ad16e](https://github.com/cioos-siooc/ckanext-fluent/tree/ce7d3b99057da1d6fb97c1e0b54e4a44040ad16e)
