### ISSUE TITLE
CKAN dataset page not all lines are converting to French - Data and Resources section

### ISSUE THREAD

**Issue by jacobthompson101** [cioos-siooc/ckan#166]
**CKAN version**
2.9.5 (on dev CKAN)

**Describe the bug**
Data and Resources section in CKAN dataset page not translated into French when switching (remains in English). 

Note that in the metadata form there is only an English entry for data resource title, but there is both an English/French entry field for data resource description. So this would also need to be updated in the metadata form. Where it says:
"Enter a description of the resource"

**Steps to reproduce**
Go to any dataset page check section: Data and Resources
https://catalogue.dev.cioosatlantic.ca/en/dataset/ca-cioos_a36e40f1-5f5b-4602-b18a-5c4f4b3f2a43

For example in English...only the heading would be French and the resources themselves remain in English:
"Data and Resources
CIOOS Atlantic ERDDAP
CIOOS Atlantic dataset ERDDAP link"

**Expected behavior**
All content should be French or English depending on selection.

**Additional details**
If possible, please provide the full stack trace of the error raised,  or add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/28519105/174654805-374e2f69-e67b-496d-ad4d-168e44b3a19f.png)

**Comment by fostermh** [comment]
done
