### ISSUE TITLE
fix the management of the dates

### ISSUE THREAD

**Issue by julieDionne** [cioos-siooc/ckan#169]
We need to fix the management of the dates in ckan/XML/metadata-form

- Date for the publication of the dataset AND the updated : Both are correct !

- The date of the data in itself, Start and End : We already have those 2 but it's not clear if it's date for data or metadata, because it's says dataset.... so can be both. A little confusing, can we rename the field "Dataset Reference Date(s)"... by something like "Data temporal extent"

- Date for the Resource creation AND update : The dates exist, but the management is not ok. The creation date must be the same as the publication date of the metadata. We must be able to manage the update date up-to-date (in the metadata form for example). For now, the date does not update or updates when the metadata is... but this is not right all the time.

For resource metadata management, perhaps a solution could be to not have those dates (which seem to be produced based on the URL and not directly based on the data and its file).
We could have a field to add a version note...

**Comment by fostermh** [comment]
done
