### ISSUE TITLE
Missing Translations on dataset detail page

### ISSUE THREAD

**Issue by sjbruce** [cioos-siooc/ckan#182]
**CKAN version**
2.9.7

**Describe the bug**
Erin caught several parts of the dataset page that are not being translated:
 - [ ] License text isn’t translated (but is in the XML)
 - [ ] The “Download Citation” button and the word “Style” aren’t translated in the Citation box
 - [ ] The update frequency isn’t translated
 - [ ] "External Organization Page" link in the organization block isn't translated

**Steps to reproduce**
Observe differences between English/French versions of a dataset page when switching languages.

**Expected behavior**
All of these sections would have bilingual counterparts.

**Additional details**

“Metadata Sources” are missing translations as well, however, this actually references the name of the specific CKAN Harvester that pulls the record into the catalogue.  This object doesn't provide a spot for translations and is for internal purposes anyway - possibly just hide for non-logged in users?

Affiliations under Contacts aren't translated either, however, the metadata form doesn't provide an option for this.  That doesn't appear to prevent the profile from supporting it, but we aren't explicitly supporting it through the metadata form and until we do this should probably be regarded as a low priroity.

**Comment by fostermh** [comment]
The license text was never intended to be bilingual. It is not pulled from the xml but rather uses the key to lookup license details in the ckan license list. If we want to support bilingual license info we should discuss with SA and metadata at the very least.

**Comment by sjbruce** [comment]
Taking a deeper look at the XML I think I see where this is coming from - the sample records from MEDS have a basic usage limitations text in place which is translated, rather than picking a specific license from the text.

https://catalogue.dev.cioosatlantic.ca/en/dataset/ca-gc-dfo-mpo-cnodc-cndoc_d029b771-475d-44aa-a97c-0bec31009f90

```
...
<mco:useLimitation xsi:type="lan:PT_FreeText_PropertyType">
  <gco:CharacterString>This dataset may be used for any purpose with appropriate citations.</gco:CharacterString>
  <lan:PT_FreeText>
    <lan:textGroup>
      <lan:LocalisedCharacterString locale="#fr">Cet ensemble de données peut être utilisé à toutes fins avec les citations appropriées.</lan:LocalisedCharacterString>
    </lan:textGroup>
  </lan:PT_FreeText>
</mco:useLimitation>
...
```

At the time I thought it was in reference to the block of text that precedes whatever the selected license is detail page of a record.

It looks like CC-BY does have multiple translations available and I imagine most government licenses do as well.  So it shouldn't be difficult for a user to find the appropriate version.

There's a version of this where the title of the licence is translated, with links - so I guess there are other permutations of this.  I don't imagine it's of high priority though.

https://catalogue.dev.cioosatlantic.ca/dataset/ca-cioos_b8482740-31d9-4dd4-87bc-cee1780dffbb

```
...
<mri:resourceConstraints>
  <mco:MD_LegalConstraints>
    <mco:reference>
      <cit:CI_Citation>
        <cit:title xsi:type="lan:PT_FreeText_PropertyType">
          <gco:CharacterString>Open Government Licence - Canada</gco:CharacterString>
          <lan:PT_FreeText>
            <lan:textGroup>
              <lan:LocalisedCharacterString locale="#fr">Licence du gouvernement ouvert – Canada </lan:LocalisedCharacterString>
            </lan:textGroup>
          </lan:PT_FreeText>
        </cit:title>
        <cit:identifier>
          <mcc:MD_Identifier>
            <mcc:code>
              <gco:CharacterString>government-open-license-canada</gco:CharacterString>
            </mcc:code>
          </mcc:MD_Identifier>
        </cit:identifier>
        <cit:onlineResource>
          <cit:CI_OnlineResource>
            <cit:linkage>
              <gco:CharacterString>
https://open.canada.ca/en/open-government-licence-canada
              </gco:CharacterString>
            </cit:linkage>
            <cit:protocol>
              <gco:CharacterString>WWW:LINK</gco:CharacterString>
            </cit:protocol>
          </cit:CI_OnlineResource>
        </cit:onlineResource>
      </cit:CI_Citation>
    </mco:reference>
    <mco:useConstraints>
      <mco:MD_RestrictionCode codeList="https://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml#MD_RestrictionCode" codeListValue="licence"/>
    </mco:useConstraints>
  </mco:MD_LegalConstraints>
</mri:resourceConstraints>
...
```
