### ISSUE TITLE
UX: datacite, rdf/xml, turtle, ... buttons vs tags

### ISSUE THREAD

**Issue by ogsletcax** [cioos-siooc/ckan#183]
A partner was thinking that the buttons datacite, rdf/xml, etc... were the tags

So it's been proposed to swap these two section places. (put tags section just after the abstract and the buttons just after the metadata source section)

Do you think it is a good idea?

@fostermh @sjbruce @jeffcullis

**Comment by fostermh** [comment]
In one of my UX examples, I moved the buttons to the sidebar which might help address this issue. We could still consider moving the keyword or better labelling them, however.

![Screen Shot 2022-03-18 at 2 22 10 PM](https://user-images.githubusercontent.com/6304992/164569222-134ac75c-8f29-4dc2-9b42-101c5f3dc628.png)

**Comment by fostermh** [comment]
I think this has been resolved by moving the links to the sidebar. please reopen if there are any more concerns.
