### ISSUE TITLE
Update ckanext-cioos_theme.po with French terms as recommended by CIOOS team

### ISSUE THREAD

**Issue by ssmosstee** [cioos-siooc/ckan#184]
My colleagues and I at ONC have noticed that the file ckanext-cioos_theme.po contains conflicts with EOV French terms as determined by the CIOOS EOV/ECV list here: https://docs.google.com/spreadsheets/d/1Df6ahH6LTjGWqlcl_iR7VB9QEagPC3Hn/edit#gid=2053037376

We are not sure which terms to use to conform to CIOOS standards, but a look into the file mentioned above seems to suggest some of these terms are pulled from Google Translate and were meant as placeholders.

**Comment by fostermh** [comment]
rather than adding translations for eov's to the i18n files I added them to the schema directly. see the [cioos schema](https://github.com/cioos-siooc/cioos-siooc-schema/pull/24/files) file for more details
