### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by timvdstap** [cioos-siooc/ckan#188]
**Describe the bug**
When adding the version number in the Metadata Entry Tool, the recommended citation displays it as '(v1.0)', whereas this is displayed as (1st ed.) in CKAN. 

**Expected behavior**
Preferred display would be (v1.0)
CKAN:
![image](https://user-images.githubusercontent.com/62965116/231014510-cda4c08f-b0b4-435d-9c27-531e397b2f90.png)

Metadata Entry Tool:
![image](https://user-images.githubusercontent.com/62965116/231014579-eed2c8bc-bbba-4272-9dff-a8542883e8f2.png)

**Comment by fostermh** [comment]
example dataset https://catalogue.hakai.org/dataset/ca-cioos_60f653ae-a3fd-484d-807c-3d7e4a0712cb
