### ISSUE TITLE
Faceting by project

### ISSUE THREAD

**Issue by timvdstap** [cioos-siooc/ckan#190]
**Is your feature request related to a problem? Please describe.**
The feature is not necessarily related to a problem but it would be great if data users and providers can easily navigate a catalogue based on records grouped by project. 

**Describe the solution you'd like**
I think it'd be great if the options from the 'project' field from the Metadata Entry Form could be listed as 'tags' (type = project) on the catalogue main page for users to select and navigate the catalogue with.

**Comment by fostermh** [comment]
this has been deployed on the hakai catalogue and appears to be working as expected.
