### ISSUE TITLE
Merge RA and National bug fixes back into core cioos code base

### ISSUE THREAD

**Issue by fostermh** [cioos-siooc/ckan#21]
We have all made small changes to the CKAN code to make things work in the interest of time. It will benefit everyone if we can merge these changes back into the CIOOS CKAN repo's.

**Solution:**
Review national and RA specific code and merge changes back to base cioos code where appropriate.

**Comment by fostermh** [comment]
addressed by pull request cioos-siooc/ckanext-cioos_theme#32

**Comment by jeffcullis** [comment]
Jacob has setup a PR for the Atlantic changes here:
https://github.com/cioos-siooc/ckanext-cioos_theme/pull/41

**Comment by fostermh** [comment]
OGSL changes merged into national already. @ogsletcax happy with how core is working.

**Comment by fostermh** [comment]
the initial intent of this issue has been completed.
