### ISSUE TITLE
Translation robot icon displays even if text was not translated automatically

### ISSUE THREAD

**Issue by robitaillej** [cioos-siooc/ckan#230]
**CKAN version**
1.6.0

**Describe the bug**
For some datasets, the small robot icon that indicates a text has been automatically translated is displayed even if the text has been written by a human. This problem is only present when using the version 1.6.0 of cioos/ckan. Tests have been made by checking or unchecking the box "I have verified this translation" in the metadata form

**Steps to reproduce**
Visit the preproduction website of SLGO (which uses the version 1.6) of [this dataset](https://catalogue.preprod.ogsl.ca/fr/dataset/ca-cioos_d75bb333-a56c-4a4d-8681-ba2bc38ebed6). You should see the icon of the robot, which should not be there. 
Visit [the same dataset](https://catalogue.ogsl.ca/fr/dataset/ca-cioos_d75bb333-a56c-4a4d-8681-ba2bc38ebed6) in production (the production website has not been updated to version 1.6 yet), and you can see the icon is not present.

**Comment by fostermh** [comment]
it appears that ckan is doing the correct thing given the package data in this case.
<img width="1151" alt="Screenshot 2024-08-12 at 11 41 27 AM" src="https://github.com/user-attachments/assets/c499cc43-8348-407b-a08a-a7f96d976f19">

the title_translation_method is set to something and thus the icon is displayed when viewing the page in french.

was the original text entered in french or english? there may be a bug in the metadata form that is not passing the correct values through to the XML. Also once the metadata form is edited and updated XML needs to be harvested by ckan before any changes will show up in the catalogue.

https://catalogue-waf.preprod.ogsl.ca/metadata-files/amundsen-science/d75bb333-a56c-4a4d-8681-ba2bc38ebed6.xml
<img width="1613" alt="Screenshot 2024-08-12 at 11 44 57 AM" src="https://github.com/user-attachments/assets/22abf3a9-e149-40d5-946c-5eaba0fe9d05">
here we can see the same values in the XML which means the XML has not been updated. 

When I look at the metadata form I see that the 'varified translation' box is not checked.
https://cioos-siooc.github.io/metadata-entry-form/#/en/stlaurent/7ukNb80dBccbfWOKNRT9ivHJden1/-NqDO0VYeN-GORmxyQmd
<img width="1309" alt="Screenshot 2024-08-12 at 11 47 53 AM" src="https://github.com/user-attachments/assets/c0d14ee6-a11c-42ba-841a-abb3594dfda1">

**Comment by robitaillej** [comment]
My bad, my colleague actually made the test with another dataset than the one given here. He checked the box indeed. The problem was actually with the cache of the page. It seems that the new version of ckan uses caching differently than the previous one! By clearing the cache it all worked out well.
