### ISSUE TITLE
Typo in the datasets page template

### ISSUE THREAD

**Issue by mcuthill** [cioos-siooc/ckan#58]
**Describe the bug**
I'm not sure if this is right place to point out this issue, but on dataset pages, 'Temporal' is spelled 'Temportal'.

**To Reproduce**
1. Go to https://catalogue.cioos.ca/
2. Click on any dataset
3. Scroll down to 'Additional Info'
4. The field 'Temportal Extent' should be 'Temporal Extent'

**Comment by fostermh** [comment]
Thanks for pointing this out @mcuthill. The spelling has been corrected but it looks like the change has not made it into production yet. @ogsletcax could you look into this please?

**Comment by fostermh** [comment]
fixed
