### ISSUE TITLE
Test spatial harvest of national CKAN into CIOOS Atlantic CKAN

### ISSUE THREAD

**Issue by jeffcullis** [cioos-siooc/ckan#73]

**Comment by jeffcullis** [comment]
On local CKAN, cleared all datasets and created a new harvest from CIOOS Atlantic production, using standard CKAN harvest and following config:
`{
  "default_tags": [{ "name": "ckan" }, { "name": "production" }],
  "default_extras": {
    "encoding": "utf8",
    "h_source_id": "{harvest_source_id}",
    "h_source_url": "{harvest_source_url}",
    "h_source_title": "{harvest_source_title}",
    "h_job_id": "{harvest_job_id}",
    "h_object_id": "{harvest_object_id}",
    "remote_ckan_base_url":"https://cioosatlantic.ca/ckan"
  },
  "clean_tags": true,
  "spatial_crs": "4326"
}`
This brought in 40 datasets. Next setup a CKAN spatial harvest from national catalogue, using following config:
`{
  "default_tags": [{ "name": "ckan" }, { "name": "production" }],
  "default_extras": {
    "encoding": "utf8",
    "h_source_id": "{harvest_source_id}",
    "h_source_url": "{harvest_source_url}",
    "h_source_title": "{harvest_source_title}",
    "h_job_id": "{harvest_job_id}",
    "h_object_id": "{harvest_object_id}"
  },
  "clean_tags": true,
  "spatial_crs": "4326",
  "spatial_filter": "POLYGON((-66.2180254597964 48.5471701713759, -60.6725462486607 48.2830997327504, -56.9035408973694 52.2201499086216, -54.9830286164566 51.9080666629733, -60.6245334416379 45.9064657851209, -64.9936988807145 46.1945426272578, -67.4903648459011 48.0910485046591, -66.2180254597964 48.5471701713759))"
}`
This brings in 92 datasets, however only 52 are from SLGO, and the rest become duplicated on my local CKAN, for a total of 132 datasets. 

Looking into the IDs for one dataset on CIOOS Atlantic production vs. National CKAN, the same dataset has equivalent GUIDs but different object IDs on each catalogue:
https://cioosatlantic.ca/ckan/api/3/action/package_show?id=c2c3e218-7704-48fa-8c18-327a5a88e28e
https://catalogue.cioos.ca/api/3/action/package_show?id=c2c3e218-7704-48fa-8c18-327a5a88e28e

**Comment by jeffcullis** [comment]
Tried setting `"organizations_filter_exclude": ["cioos-atlantic"],` in the local harvest from national, however this only resulted in 7 datasets being filtered out, not all 40.

**Comment by jeffcullis** [comment]
Cleared all national harvest datasets on local. The output of
http://localhost:5000/api/3/action/package_show?id=c2c3e218-7704-48fa-8c18-327a5a88e28e
showed the same object ID for this dataset as in CIOOS Atlantic production.
`{"key": "h_object_id", "value": "2bd760b9-c9f1-4a19-b81c-6ab925f26b25"}`
So the standard CKAN harvest preserves the object IDs as expected. But for some reason the National harvest object ID has diverged from the Atlantic object ID. Fixing the issue may be as simple as clearing the datasets from CIOOS Atlantic from National and re-harvesting them.

**Comment by jeffcullis** [comment]
The object ID is not the relevant ID, instead we want to ensure the same package_id, e.g.
"package_id": "bb9eef80-6b4e-438a-bf4c-b32d31159c4c"
The divergence is likely due to Atlantic clearing and re-harvesting datasets. This might be fixed by adding force_all to the national harvest configuration

> force_all: By default, after the first harvesting, the harvester will gather only the modified packages from the remote site since the last harvesting. Setting this property to true will force the harvester to gather all remote packages regardless of the modification date. Default is False.

**Comment by jeffcullis** [comment]
Added Atlantic bioregions and a more basic version that I manually traced in QGIS:
https://github.com/cioos-siooc/cioos-siooc-schema/tree/atlantic_polygon
The original was obtained by selecting the relevant portions from Scott's bioregions geojson file here:
https://github.com/cioos-siooc/cioos-siooc_data_transform/blob/odf_transform_sbruce/odf_transform/geojson_files/DFO_Marine_Bioregions_simplified_0.05_fixed.geojson

Cloned the schema repo and checked out atlantic_polygon branch to the src folder on the running CKAN containers.

Added to harvest config:
`"spatial_filter_file": "cioos-siooc-schema/atlantic_bioregions_basic.wkt"`

It seems that the existing atlantic.wkt doesn't pass validation, and neither does the full atlantic_bioregions.wkt file, however 
the very basic one I created does work.

Note that spaces must be removed before opening bracket in 'POLYGON (' or 'MULTIPOLYGON (...', and spaces must be added before initial coordinates for it to pass validation, which is performed via the regexes regex_poly and regex_multipoly found here:
`ckanext\harvest\harvesters\ckanspatialharvester.py`

After harvesting production to local, then harvesting national to local using spatial harvest with the file indicated above, no files were added, got 132 errors of form:

`983eb31d-329c-4a46-8212-9b80cb9ca735
string indices must be integers`

**Comment by fostermh** [comment]
the more complex files not passing validation makes sense as they appear to be of type 'FeatureCollection' and I think the code assumes a more basic polygon or multi-polygon. If This is an issue we could work on a more robust validator. it is quite simple at the moment. Strange it is not harvesting correctly. I will test on my end as well.

**Comment by fostermh** [comment]
URL: `https://catalogue.cioos.ca/`
Source `Type: CKAN Spatial`
Config: 
```json
{
  "default_tags": [],
  "default_extras": {
    "encoding": "utf8",
    "h_source_id": "{harvest_source_id}",
    "h_source_url": "{harvest_source_url}",
    "h_source_title": "{harvest_source_title}",
    "h_job_id": "{harvest_job_id}",
    "h_object_id": "{harvest_object_id}"
  },
  "clean_tags": true,
  "remote_groups": "false",
  "remote_orgs": "false",
  "validate_packages": true,
  "spatial_filter_file": "./cioos-siooc-schema/atlantic_bioregions_basic.wkt"
}
```
seems to work for me. I'm using the latest cioos/ckan image. Harvester found 132 datasets. harvest 71. I may have stopped it early. Your config is likely different so results may vary.

**Comment by fostermh** [comment]
seems to work.
