### ISSUE TITLE
Add regional open data licenses

### ISSUE THREAD

**Issue by jeffcullis** [cioos-siooc/ckan#85]
We'd like to add support for the NS open data license:
https://novascotia.ca/opendata/licence.asp

While we're at it, we may also want to add the NL open data license:
https://opendata.gov.nl.ca/public/opendata/page/?page-id=licence

Cross-posted to metadata form repo as well:
https://github.com/cioos-siooc/metadata-entry-form/issues/89

**Comment by fostermh** [comment]
Add a license to [/ckan/contrib/docker/src/cioos-siooc-schema/ckan_license.json](https://github.com/cioos-siooc/cioos-siooc-schema/blob/master/ckan_license.json) to update the available licenses in ckan. Note that the `id` used in the license file and the one provided in the xml metadata should match.

Should likely add the (government of canada open data license)[https://open.canada.ca/en/open-government-licence-canada] and [Open Government Licence - British Columbia](https://www2.gov.bc.ca/gov/content/data/open-data/open-government-licence-bc) as well.

We could also consider adding [Open Government Licence – Ontario](https://www.ontario.ca/page/open-government-licence-ontario) and presumably there is one for Quebec but I did not find it in my quick google search.
