### ISSUE TITLE
Add citation export feature

### ISSUE THREAD

**Issue by ogsletcax** [cioos-siooc/ckan#95]
Currently a dataset citation cannot be exported in a standard format

can we have something similar as:
https://dataverse.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5683/SP2/RZDGPI

"cite dataset" button ?

**Comment by fostermh** [comment]
o I expect so.
see cioos-siooc/ckan#30
I'm just finishing it up now.

**Comment by fostermh** [comment]
done.
